name: Test unit
on:
  push:
    branches:
      - '**'

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:     
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'
     
      - name: Install dependencies
        run: dotnet restore --verbosity quiet
        
      - name: Build
        run: dotnet build --no-restore /clp:ErrorsOnly /p:GeneratePackageOnBuild=false --verbosity quiet
        
      - name: Test
        run: |
          cd bench/AELF.Benchmark
          dotnet run --filter '*MinerTests*' '*MiningTxHubBenchmark*'
