name: Test unit
on:
  push:
    branches:
      - '**'

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  Solution_Name: AElf.All.sln 
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:     
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
     
      - name: Install dependencies
        run: dotnet restore AElf.All.sln --verbosity quiet
        
      - name: Build
        run: dotnet build AElf.All.sln --no-restore /clp:ErrorsOnly /p:GeneratePackageOnBuild=false --verbosity quiet
        
      - name: Test
        run: |
          ls
          pwd
          cd bench/AElf.Benchmark
          dotnet run --filter '*MinerTests*' '*MiningTxHubBenchmark*'
