name: Test unit
on:
  push:
    branches:
      - '**'

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  Solution_Name: AElf.All.sln 
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:     
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      - name: 'Download AElf build tools'
        run: bash scripts/download_binary.sh
        
      - name: 'Install protobuf'
        run: bash scripts/install_protobuf.sh
     
        
      - name: Build
        # run: dotnet build  bench/AElf.Benchmark/AElf.Benchmark.csproj --no-restore /clp:ErrorsOnly /p:GeneratePackageOnBuild=false --verbosity quiet
        run:  bash build.sh 
      
      - name: Test
        run: |
          pwd
          cd bench/AElf.Benchmark
          dotnet run --filter '*MinerTests*' '*MiningTxHubBenchmark*'
